### ISSUE TITLE
Tunnel not working

### ISSUE THREAD

**Issue by HugoGresse** [LuisBoto/ngrok-tunnel-action#3]
I can't seems to make it work on GitHub action, self hosted runner, while downloaded the latest build from ngrok and starting it manually work without issue. 

Action: 
```
            -   uses: luisboto/ngrok-tunnel-action@v0.1.7.2
                with:
                    timeout: 1h
                    port: 3000
                    tunnel_type: http
                    ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
```

Logs: 
```

2023-11-14 16:30:34 (9.27 MB/s) - ‘ngrok-stable-linux-amd64.zip’ saved [13921656/13921656]
Run unzip -qq ngrok-stable-linux-amd64.zip
  
Run ./ngrok authtoken ***
  ./ngrok authtoken ***
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Authtoken saved to configuration file: /builds/.ngrok2/ngrok.yml
Run ( timeout 1h ./ngrok http 3000 ) &
  ( timeout 1h ./ngrok http 3000 ) &
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  
Run echo "::set-output name=tunnel-url::$( curl http://127.0.0.1:4040/api/tunnels | jq -r ".tunnels[0].public_url" )"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    36  100    36    0     0  17191      0 --:--:-- --:--:-- --:--:-- 36000
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Run echo null
  echo null
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
null
```

any idea ?
